-- Export de la table `vw_disables_with_labels`
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `vw_disables_with_labels`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `vw_disables_with_labels` AS select case when `disables`.`sourceType` = 0 then 'DISABLE_TYPE_SPELL' when `disables`.`sourceType` = 1 then 'DISABLE_TYPE_QUEST' when `disables`.`sourceType` = 2 then 'DISABLE_TYPE_MAP' when `disables`.`sourceType` = 3 then 'DISABLE_TYPE_BATTLEGROUND' when `disables`.`sourceType` = 4 then 'DISABLE_TYPE_ACHIEVEMENT_CRITERIA' when `disables`.`sourceType` = 5 then 'DISABLE_TYPE_OUTDOORPVP' when `disables`.`sourceType` = 6 then 'DISABLE_TYPE_VMAP' when `disables`.`sourceType` = 7 then 'DISABLE_TYPE_MMAP' when `disables`.`sourceType` = 8 then 'DISABLE_TYPE_LFG_MAP' else `disables`.`sourceType` end AS `sourceType`,`disables`.`entry` AS `entry`,`disables`.`flags` AS `flags`,`disables`.`params_0` AS `params_0`,`disables`.`params_1` AS `params_1`,`disables`.`comment` AS `comment` from `disables`;

INSERT INTO `vw_disables_with_labels` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES
('DISABLE_TYPE_SPELL', 128, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 698, 17, '30,489', '', 'Disable of Ritual of Summoning on Alterac Valley and Warsong Gulch'),
('DISABLE_TYPE_SPELL', 758, 8, '', '', 'Spell for deprecated item 1254'),
('DISABLE_TYPE_SPELL', 2825, 64, '', '', 'Ignore LOS for Heroism'),
('DISABLE_TYPE_SPELL', 16378, 64, '', '', 'Ignore LOS for Krakles Thermometer'),
('DISABLE_TYPE_SPELL', 17639, 256, '0', '0', 'Wail of the Banshee'),
('DISABLE_TYPE_SPELL', 17729, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 17730, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 17945, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 17947, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 17949, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 20318, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 20319, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 20321, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 20397, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 23480, 8, '', '', 'Spell for deprecated item 1254'),
('DISABLE_TYPE_SPELL', 23481, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 23482, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 23483, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 23789, 8, '', '', 'Stoneclaw Totem TEST - can crash client by spawning too many totems'),
('DISABLE_TYPE_SPELL', 24745, 64, '', '', 'Summon Templar, Trigger ignores LoS'),
('DISABLE_TYPE_SPELL', 24747, 64, '', '', 'Summon Templar Fire, Trigger ignores LoS'),
('DISABLE_TYPE_SPELL', 24757, 64, '', '', 'Summon Templar Air, Trigger ignores LoS'),
('DISABLE_TYPE_SPELL', 24759, 64, '', '', 'Summon Templar Earth, Trigger ignores LoS'),
('DISABLE_TYPE_SPELL', 24761, 64, '', '', 'Summon Templar Water, Trigger ignores LoS'),
('DISABLE_TYPE_SPELL', 24762, 64, '', '', 'Summon Duke, Trigger ignores LoS'),
('DISABLE_TYPE_SPELL', 24766, 64, '', '', 'Summon Duke Fire, Trigger ignores LoS'),
('DISABLE_TYPE_SPELL', 24769, 64, '', '', 'Summon Duke Air, Trigger ignores LoS'),
('DISABLE_TYPE_SPELL', 24771, 64, '', '', 'Summon Duke Earth, Trigger ignores LoS'),
('DISABLE_TYPE_SPELL', 24773, 64, '', '', 'Summon Duke Water, Trigger ignores LoS'),
('DISABLE_TYPE_SPELL', 24785, 64, '', '', 'Summon Royal, Trigger ignores LoS'),
('DISABLE_TYPE_SPELL', 24787, 64, '', '', 'Summon Royal Fire, Trigger ignores LoS'),
('DISABLE_TYPE_SPELL', 24791, 64, '', '', 'Summon Royal Air, Trigger ignores LoS'),
('DISABLE_TYPE_SPELL', 24792, 64, '', '', 'Summon Royal Earth, Trigger ignores LoS'),
('DISABLE_TYPE_SPELL', 24793, 64, '', '', 'Summon Royal Water, Trigger ignores LoS'),
('DISABLE_TYPE_SPELL', 24803, 64, '', '', 'Abyssal Punishment ignores LoS'),
('DISABLE_TYPE_SPELL', 27252, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 27256, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 27892, 64, '', '', 'Gothik - To Anchor 1 - Ignore LoS'),
('DISABLE_TYPE_SPELL', 27893, 64, '', '', 'Gothik - To Anchor 2 - Ignore LoS'),
('DISABLE_TYPE_SPELL', 27915, 64, '', '', 'Gothik - Anchor To Skulls - Ignore LoS'),
('DISABLE_TYPE_SPELL', 27928, 64, '', '', 'Gothik - To Anchor 1 - Ignore LoS'),
('DISABLE_TYPE_SPELL', 27929, 64, '', '', 'Gothik - To Anchor 2 - Ignore LoS'),
('DISABLE_TYPE_SPELL', 27931, 64, '', '', 'Gothik - Anchor To Skulls - Ignore LoS'),
('DISABLE_TYPE_SPELL', 27935, 64, '', '', 'Gothik - To Anchor 1 - Ignore LoS'),
('DISABLE_TYPE_SPELL', 27936, 64, '', '', 'Gothik - To Anchor 2 - Ignore LoS'),
('DISABLE_TYPE_SPELL', 27937, 64, '', '', 'Gothik - Anchor To Skulls - Ignore LoS'),
('DISABLE_TYPE_SPELL', 28096, 64, '', '', 'Stalagg Tesla Visual - Ignore LoS'),
('DISABLE_TYPE_SPELL', 28098, 64, '', '', 'Stalagg Tesla Periodic - Ignore LoS'),
('DISABLE_TYPE_SPELL', 28110, 64, '', '', 'Feugen Tesla Periodic - Ignore LoS'),
('DISABLE_TYPE_SPELL', 28111, 64, '', '', 'Feugen Tesla Visual - Ignore LoS'),
('DISABLE_TYPE_SPELL', 28170, 8, '', '', 'Spell for deprecated item'),
('DISABLE_TYPE_SPELL', 29443, 256, '0', '0', 'Clutch of Foresight'),
('DISABLE_TYPE_SPELL', 29916, 64, '', '', 'Ignore LOS on Feed Captured Animal'),
('DISABLE_TYPE_SPELL', 29917, 64, '', '', 'Ignore LOS on Feed Captured Animal'),
('DISABLE_TYPE_SPELL', 31696, 64, '', '', 'Ignore LOS on Thane'),
('DISABLE_TYPE_SPELL', 32182, 64, '', '', 'Ignore LOS for Bloodlust'),
('DISABLE_TYPE_SPELL', 32205, 64, '', '', 'Ignore LOS for Place Mag\'har Battle Standard'),
('DISABLE_TYPE_SPELL', 34209, 64, '', '', 'Ignore LOS on Blue Beam'),
('DISABLE_TYPE_SPELL', 34211, 64, '', '', 'Ignore LOS on Blue Beam'),
('DISABLE_TYPE_SPELL', 34212, 64, '', '', 'Ignore LOS on Blue Beam'),
('DISABLE_TYPE_SPELL', 35515, 64, '', '', 'Ignore LOS on Salaadin\'s Tesla'),
('DISABLE_TYPE_SPELL', 45425, 64, '', '', 'Ignore LOS for Shoot (Dummy)'),
('DISABLE_TYPE_SPELL', 45537, 64, '', '', 'Lightning Beam Channel - Ignore LOS'),
('DISABLE_TYPE_SPELL', 45724, 64, '0', '0', 'Disable LoS for spell Braziers Hit'),
('DISABLE_TYPE_SPELL', 46314, 64, '0', '0', 'Disable LOS for spell Ahune - Slippery Floor Ambient'),
('DISABLE_TYPE_SPELL', 46422, 64, '0', '0', 'Disable LOS for spell Shamans Look for Opening'),
('DISABLE_TYPE_SPELL', 46593, 64, '0', '0', 'Disable LOS for spell Whisp Flight Missile and Beam'),
('DISABLE_TYPE_SPELL', 46603, 64, '0', '0', 'Disable LOS for spell Force Whisp to Flight'),
('DISABLE_TYPE_SPELL', 46836, 64, '0', '', 'Spell Flame Patch - Ignore LOS'),
('DISABLE_TYPE_SPELL', 46842, 64, '0', '', 'Spell Flame Ring - Ignore LOS'),
('DISABLE_TYPE_SPELL', 47117, 64, '', '', 'Ignore LOS on Script Cast Summon Image of Drakuru 01'),
('DISABLE_TYPE_SPELL', 47149, 64, '', '', 'Ignore LOS on Script Cast Summon Image of Drakuru 02'),
('DISABLE_TYPE_SPELL', 47316, 64, '', '', 'Ignore LOS on Script Cast Summon Image of Drakuru 03'),
('DISABLE_TYPE_SPELL', 47405, 64, '', '', 'Ignore LOS on Script Cast Summon Image of Drakuru 04'),
('DISABLE_TYPE_SPELL', 49308, 64, '0', '0', 'Disable LoS for spell Utgard Pinacle Reset Check'),
('DISABLE_TYPE_SPELL', 49590, 64, '', '', ''),
('DISABLE_TYPE_SPELL', 50313, 64, '0', '0', 'Disable LOS for Spell Mole Machine Emerge'),
('DISABLE_TYPE_SPELL', 50439, 64, '', '', 'Ignore LOS on Script Cast Summon Image of Drakuru 05'),
('DISABLE_TYPE_SPELL', 50563, 64, '', '', 'Ignore LOS for Carve Stone'),
('DISABLE_TYPE_SPELL', 52212, 64, '', '', 'Disable LoS for Spell Death and Decay'),
('DISABLE_TYPE_SPELL', 52228, 64, '', '', 'Disable LOS check for Kill Credit (quest 12669)'),
('DISABLE_TYPE_SPELL', 52479, 64, '', '', 'Gift of the Harvester (LOS)'),
('DISABLE_TYPE_SPELL', 54114, 64, '0', '0', 'Heart of the Phoenix uses Cooldown, but won\'t work through LoS, so ignore LoS.'),
('DISABLE_TYPE_SPELL', 54612, 64, '', '', 'Chained Peasant (Chest) LOS'),
('DISABLE_TYPE_SPELL', 56940, 64, '', '', 'Disable LOS check for Thorim Story Kill Credit'),
('DISABLE_TYPE_SPELL', 58518, 64, '', '', 'Ignore LOS on Ahn kahet Brazier Kill Credit'),
('DISABLE_TYPE_SPELL', 59661, 64, '', '', 'Icecrown Purple Beam (Ignore Los)'),
('DISABLE_TYPE_SPELL', 61904, 8, '', '', 'Magma Totem TEST - can crash client by spawning too many totems'),
('DISABLE_TYPE_SPELL', 62042, 64, '', '', 'Stormhammer - Ignore LOS'),
('DISABLE_TYPE_SPELL', 62266, 64, '0', '0', 'Disable LOS for Spell Trigger 3 adds'),
('DISABLE_TYPE_SPELL', 62272, 64, '0', '0', 'Disable LOS for spell Raelorasz\' Spark'),
('DISABLE_TYPE_SPELL', 64767, 64, '', '', 'Stormhammer - Ignore LOS'),
('DISABLE_TYPE_SPELL', 66636, 64, '0', '0', 'Disable LoS for Spell Rising Anger'),
('DISABLE_TYPE_SPELL', 69922, 64, '', '', 'Ignore LOS on Temper Quel Delar'),
('DISABLE_TYPE_SPELL', 69956, 64, '', '', 'Ignore LOS on Return Tempered Quel Delar'),
('DISABLE_TYPE_SPELL', 70460, 64, '', '', 'Ignore LOS for Coldflame Jets'),
('DISABLE_TYPE_SPELL', 71599, 64, '', '', 'Ignore LOS for Cosmetic - Explosion (Chemical Wagon)'),
('DISABLE_TYPE_QUEST', 1, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 73, 0, '', '', 'Deprecated quest: <TXT> No Reward'),
('DISABLE_TYPE_QUEST', 108, 0, '', '', 'Deprecated quest: <TXT> Mystery Reward'),
('DISABLE_TYPE_QUEST', 137, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 241, 0, '', '', 'Deprecated quest: <TEST> HEY MISTER WILSON!'),
('DISABLE_TYPE_QUEST', 242, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 259, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 260, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 316, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 326, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 327, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 352, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 390, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 402, 0, '', '', 'Deprecated quest: Sirra is Busy'),
('DISABLE_TYPE_QUEST', 406, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 462, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 490, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 497, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 526, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 534, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 548, 0, '', '', 'Deprecated quest: <NYI> <TXT> Bloodstone Pendant'),
('DISABLE_TYPE_QUEST', 550, 0, '', '', 'Deprecated quest: Battle of Hillsbrad'),
('DISABLE_TYPE_QUEST', 612, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 620, 0, '', '', 'Deprecated quest: The Monogrammed Sash'),
('DISABLE_TYPE_QUEST', 636, 0, '', '', 'Deprecated quest: Legends of the Earth <NYI>'),
('DISABLE_TYPE_QUEST', 740, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 774, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 785, 0, '', '', 'Deprecated quest: A Strategic Alliance'),
('DISABLE_TYPE_QUEST', 787, 0, '', '', 'Deprecated quest: The New Horde'),
('DISABLE_TYPE_QUEST', 796, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 797, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 798, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 799, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 800, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 801, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 802, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 803, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 807, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 810, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 811, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 814, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 820, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 839, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 856, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 859, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 904, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 908, 0, '', '', 'Deprecated quest: A Strategic Alliance'),
('DISABLE_TYPE_QUEST', 909, 0, '', '', 'Deprecated quest: A Strategic Alliance'),
('DISABLE_TYPE_QUEST', 912, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 946, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 960, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 987, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 988, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 989, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 1128, 0, '', '', 'Deprecated quest: <NYI> The Gnome Pit Crew is Thirsty'),
('DISABLE_TYPE_QUEST', 1129, 0, '', '', 'Deprecated quest: <NYI> The Goblin Pit Crew is Thirsty'),
('DISABLE_TYPE_QUEST', 1155, 0, '', '', 'Deprecated quest: <NYI> <TXT> bug crystal side quest'),
('DISABLE_TYPE_QUEST', 1156, 0, '', '', 'Deprecated quest: <NYI> <TXT> speak to alchemist pestlezugg'),
('DISABLE_TYPE_QUEST', 1157, 0, '', '', 'Deprecated quest: <NYI> <TXT> pestlezugg needs items'),
('DISABLE_TYPE_QUEST', 1158, 0, '', '', 'Deprecated quest: <NYI> <TXT> speak to rabine saturna'),
('DISABLE_TYPE_QUEST', 1161, 0, '', '', 'Deprecated quest: <NYI> <TXT> gossip shade of ambermoon'),
('DISABLE_TYPE_QUEST', 1162, 0, '', '', 'Deprecated quest: <NYI> <TXT> speak to hamuul runetotem'),
('DISABLE_TYPE_QUEST', 1163, 0, '', '', 'Deprecated quest: <NYI> <TXT> speak to tyrande whisperwind'),
('DISABLE_TYPE_QUEST', 1165, 0, '', '', 'Deprecated quest: <NYI> Ore for the Races'),
('DISABLE_TYPE_QUEST', 1174, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 1263, 0, '', '', 'Deprecated quest: The Burning Inn <CHANGE TO GOSSIP>'),
('DISABLE_TYPE_QUEST', 1272, 0, '', '', 'Deprecated quest: Finding Reethe <CHANGE INTO GOSSIP>'),
('DISABLE_TYPE_QUEST', 1277, 0, '', '', 'Deprecated quest: <nyi> <TXT> The Centaur Hoofprints'),
('DISABLE_TYPE_QUEST', 1278, 0, '', '', 'Deprecated quest: <nyi> <TXT> The Grim Totem Clan'),
('DISABLE_TYPE_QUEST', 1279, 0, '', '', 'Deprecated quest: <nyi> <TXT>The Centaur Hoofprints'),
('DISABLE_TYPE_QUEST', 1280, 0, '', '', 'Deprecated quest: <nyi> <TXT>The Centaur Hoofprints'),
('DISABLE_TYPE_QUEST', 1281, 0, '', '', 'Deprecated quest: Jim\'s Song <CHANGE TO GOSSIP>'),
('DISABLE_TYPE_QUEST', 1283, 0, '', '', 'Deprecated quest: Fire at the Shady Rest <CHANGE TO GOSSIP>'),
('DISABLE_TYPE_QUEST', 1289, 0, '', '', 'Deprecated quest: <nyi> Vimes\'s Report'),
('DISABLE_TYPE_QUEST', 1290, 0, '', '', 'Deprecated quest: <nyi> Investigating Mosarn'),
('DISABLE_TYPE_QUEST', 1291, 0, '', '', 'Deprecated quest: <nyi> <TXT> Centaur Hoofprints'),
('DISABLE_TYPE_QUEST', 1292, 0, '', '', 'Deprecated quest: <nyi><TXT> Centaur Hoofprints'),
('DISABLE_TYPE_QUEST', 1293, 0, '', '', 'Deprecated quest: <nyi> <TXT> Centaur Hoofprints'),
('DISABLE_TYPE_QUEST', 1294, 0, '', '', 'Deprecated quest: <nyi> <TXT>Centaur Sympathies'),
('DISABLE_TYPE_QUEST', 1295, 0, '', '', 'Deprecated quest: <nyi> <TXT> Course of Action'),
('DISABLE_TYPE_QUEST', 1296, 0, '', '', 'Deprecated quest: <nyi> <TXT> Course of Action'),
('DISABLE_TYPE_QUEST', 1297, 0, '', '', 'Deprecated quest: <nyi> <TXT> Course of Action'),
('DISABLE_TYPE_QUEST', 1298, 0, '', '', 'Deprecated quest: <nyi> <TXT> Thrall\'s Dirty Work'),
('DISABLE_TYPE_QUEST', 1299, 0, '', '', 'Deprecated quest: <nyi> <TXT> Thrall\'s Dirty Work'),
('DISABLE_TYPE_QUEST', 1300, 0, '', '', 'Deprecated quest: <nyi> <TXT> Lorn Grim Totem'),
('DISABLE_TYPE_QUEST', 1318, 0, '', '', 'Unfinished Gordok Business replaced by 7703'),
('DISABLE_TYPE_QUEST', 1390, 0, '', '', 'Deprecated quest: <nyi> Oops, We Killed Them Again.'),
('DISABLE_TYPE_QUEST', 1397, 0, '', '', 'Deprecated quest: <nyi> Saved!'),
('DISABLE_TYPE_QUEST', 1441, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 1443, 0, '', '', 'Deprecated quest: <nyi> The Shakedown'),
('DISABLE_TYPE_QUEST', 1460, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 1461, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 1533, 0, '', '', 'Deprecated quest: <NYI> Call of Air'),
('DISABLE_TYPE_QUEST', 1537, 0, '', '', 'Deprecated quest: <NYI> Call of Air'),
('DISABLE_TYPE_QUEST', 1538, 0, '', '', 'Deprecated quest: <NYI> Call of Air'),
('DISABLE_TYPE_QUEST', 1659, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 1660, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 1662, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 1663, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 1664, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 2018, 0, '', '', 'Deprecated quest: Rokar\'s Test'),
('DISABLE_TYPE_QUEST', 2020, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 2058, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 2059, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 2868, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 2971, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3023, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3064, 0, '', '', 'Deprecated quest: <NYI> <TXT> Pirate Hats'),
('DISABLE_TYPE_QUEST', 3111, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 3241, 0, '', '', 'Deprecated quest: <NYI> <TXT><redux> Dreadmist Peak'),
('DISABLE_TYPE_QUEST', 3383, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3384, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 3401, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3403, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3404, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3405, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3422, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3423, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3424, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3425, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3515, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3516, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3529, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3530, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3531, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3581, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 3622, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3623, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3624, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 3631, 0, '', '', 'Deprecated quest: Summon Felsteed'),
('DISABLE_TYPE_QUEST', 3644, 0, '', '', 'Depracted quest Membership Card Renewal'),
('DISABLE_TYPE_QUEST', 3645, 0, '', '', 'Depracted quest Membership Card Renewal'),
('DISABLE_TYPE_QUEST', 3646, 0, '', '', 'Depracted quest Membership Card Renewal'),
('DISABLE_TYPE_QUEST', 3647, 0, '', '', 'Depracted quest Membership Card Renewal'),
('DISABLE_TYPE_QUEST', 3885, 0, '', '', 'Deprecated quest: <NYI> <TXT> The Gadgetzan Run'),
('DISABLE_TYPE_QUEST', 3910, 0, '', '', 'Deprecated quest: <NYI> <TXT> The Un\'Goro Run'),
('DISABLE_TYPE_QUEST', 4183, 0, '', '', 'Deprecated quest: The True Masters'),
('DISABLE_TYPE_QUEST', 4184, 0, '', '', 'Deprecated quest: The True Masters'),
('DISABLE_TYPE_QUEST', 4185, 0, '', '', 'Deprecated quest: The True Masters'),
('DISABLE_TYPE_QUEST', 4186, 0, '', '', 'Deprecated quest: The True Masters'),
('DISABLE_TYPE_QUEST', 4223, 0, '', '', 'Deprecated quest: The True Masters'),
('DISABLE_TYPE_QUEST', 4224, 0, '', '', 'Deprecated quest: The True Masters'),
('DISABLE_TYPE_QUEST', 4299, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 4323, 0, '', '', 'Deprecated quest: <NYI> <TXT> Get those Hyenas!!!'),
('DISABLE_TYPE_QUEST', 4485, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 4486, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 4487, 0, '', '', 'Deprecated quest: Summon Felsteed'),
('DISABLE_TYPE_QUEST', 4488, 0, '', '', 'Deprecated quest: Summon Felsteed'),
('DISABLE_TYPE_QUEST', 4489, 0, '', '', 'Deprecated quest: Summon Felsteed'),
('DISABLE_TYPE_QUEST', 4490, 0, '', '', 'Deprecated quest: Summon Felsteed'),
('DISABLE_TYPE_QUEST', 4541, 0, '', '', 'Deprecated quest: <NYI> <TXT>'),
('DISABLE_TYPE_QUEST', 4905, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5053, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5101, 0, '', '', 'Deprecated quest: Lee\'s Ultimate Test Quest... of Doom!'),
('DISABLE_TYPE_QUEST', 5205, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5207, 0, '', '', 'Deprecated quest: <NYI> <TXT> The True Summoner'),
('DISABLE_TYPE_QUEST', 5208, 0, '', '', 'Deprecated quest: <NYI> <TXT> The Blessing of Evil'),
('DISABLE_TYPE_QUEST', 5303, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5304, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5383, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5506, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5512, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5516, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5520, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5523, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5530, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5532, 0, '', '', 'Deprecated quest: <NYI> <TXT> Ring of the Dawn'),
('DISABLE_TYPE_QUEST', 5627, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5628, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5629, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5630, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5631, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5632, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5633, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5634, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5635, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5636, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5637, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5638, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5639, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5640, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5641, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5642, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5643, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5644, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5645, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5646, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5647, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5652, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5653, 0, '', '', 'Deprecated quest: <NYI> Hex of Weakness'),
('DISABLE_TYPE_QUEST', 5654, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5655, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5656, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5657, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5658, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5659, 0, '', '', 'Deprecated quest: <NYI> Touch of Weakness'),
('DISABLE_TYPE_QUEST', 5660, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5661, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5662, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5663, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5664, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5665, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5666, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5667, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5668, 0, '', '', 'Deprecated quest: <NYI> A Blessing of Light'),
('DISABLE_TYPE_QUEST', 5669, 0, '', '', 'Deprecated quest: <NYI> A Blessing of Light'),
('DISABLE_TYPE_QUEST', 5670, 0, '', '', 'Deprecated quest: <NYI> A Blessing of Light'),
('DISABLE_TYPE_QUEST', 5671, 0, '', '', 'Deprecated quest: <NYI> A Blessing of Light'),
('DISABLE_TYPE_QUEST', 5672, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5673, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5674, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5675, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5676, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5677, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5678, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5679, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5680, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 5681, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5682, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5683, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5684, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5685, 0, '', '', 'Deprecated quest: <NYI> <TXT> The Light Protects You'),
('DISABLE_TYPE_QUEST', 5686, 0, '', '', 'Deprecated quest: <NYI> The Light Protects You'),
('DISABLE_TYPE_QUEST', 5687, 0, '', '', 'Deprecated quest: <NYI> The Light Protects You'),
('DISABLE_TYPE_QUEST', 5688, 0, '', '', 'Deprecated quest: <NYI> <TXT> A Touch of Voodoo'),
('DISABLE_TYPE_QUEST', 5689, 0, '', '', 'Deprecated quest: <NYI> A Touch of Voodoo'),
('DISABLE_TYPE_QUEST', 5690, 0, '', '', 'Deprecated quest: <NYI> <TXT> A Touch of Voodoo'),
('DISABLE_TYPE_QUEST', 5691, 0, '', '', 'Deprecated quest: <NYI> <TXT> In the Dark it was Created'),
('DISABLE_TYPE_QUEST', 5692, 0, '', '', 'Deprecated quest: <NYI> In the Dark It was Created'),
('DISABLE_TYPE_QUEST', 5693, 0, '', '', 'Deprecated quest: <NYI> In the Dark It was Created'),
('DISABLE_TYPE_QUEST', 5694, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5695, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5696, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5697, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 5698, 0, '', '', 'Deprecated quest: <NYI> <TXT> A Small Amount of Hope'),
('DISABLE_TYPE_QUEST', 5699, 0, '', '', 'Deprecated quest: <NYI> A Small Amount of Hope'),
('DISABLE_TYPE_QUEST', 5700, 0, '', '', 'Deprecated quest: <NYI> A Small Amount of Hope'),
('DISABLE_TYPE_QUEST', 5701, 0, '', '', 'Deprecated quest: <NYI> <TXT> The Rites of Old'),
('DISABLE_TYPE_QUEST', 5702, 0, '', '', 'Deprecated quest: <NYI> The Rites of Old'),
('DISABLE_TYPE_QUEST', 5703, 0, '', '', 'Deprecated quest: <NYI> The Rites of Old'),
('DISABLE_TYPE_QUEST', 5704, 0, '', '', 'Deprecated quest: <NYI> <TXT> Undead Priest Robe'),
('DISABLE_TYPE_QUEST', 5705, 0, '', '', 'Deprecated quest: <NYI> No Longer a Shadow'),
('DISABLE_TYPE_QUEST', 5706, 0, '', '', 'Deprecated quest: <NYI> No Longer a Shadow'),
('DISABLE_TYPE_QUEST', 5707, 0, '', '', 'Deprecated quest: <NYI> <TXT> Flirting With Darkness'),
('DISABLE_TYPE_QUEST', 5708, 0, '', '', 'Deprecated quest: <NYI> Flirting With Darkness'),
('DISABLE_TYPE_QUEST', 5709, 0, '', '', 'Deprecated quest: <NYI> Flirting With Darkness'),
('DISABLE_TYPE_QUEST', 5710, 0, '', '', 'Deprecated quest: <NYI> <TXT> Troll Priest Robe'),
('DISABLE_TYPE_QUEST', 5711, 0, '', '', 'Deprecated quest: <NYI> The Lost Ways'),
('DISABLE_TYPE_QUEST', 5712, 0, '', '', 'Deprecated quest: <NYI> The Lost Ways'),
('DISABLE_TYPE_QUEST', 6003, 0, '', '', 'Deprecated quest: <nyi> <txt> Green With Envy'),
('DISABLE_TYPE_QUEST', 6145, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 6165, 0, '', '', 'Deprecated quest: <NYI> <TXT> Archmage Timolain\'s Remains'),
('DISABLE_TYPE_QUEST', 6201, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 6202, 0, '', '', 'Deprecated quest: <UNUSED> Good and Evil'),
('DISABLE_TYPE_QUEST', 6702, 0, '', '', 'Deprecated quest: <TXT> SF,RFK,GNOMER,BF'),
('DISABLE_TYPE_QUEST', 6703, 0, '', '', 'Deprecated quest: <TXT> SF,RFK,GNOMER,BF - Repeatable'),
('DISABLE_TYPE_QUEST', 6704, 0, '', '', 'Deprecated quest: <TXT> SM,RFD,ULD'),
('DISABLE_TYPE_QUEST', 6705, 0, '', '', 'Deprecated quest: <TXT> SM,RFD,ULD - Repeatable'),
('DISABLE_TYPE_QUEST', 6706, 0, '', '', 'Deprecated quest: <TXT> ZUL,ST,MAR'),
('DISABLE_TYPE_QUEST', 6707, 0, '', '', 'Deprecated quest: <TXT> ZUL,ST,MAR - Repeatable'),
('DISABLE_TYPE_QUEST', 6708, 0, '', '', 'Deprecated quest: <TXT> BRD,DM,BRS'),
('DISABLE_TYPE_QUEST', 6709, 0, '', '', 'Deprecated quest: <TXT> BRD,DM,BRS - Repeatable'),
('DISABLE_TYPE_QUEST', 6710, 0, '', '', 'Deprecated quest: <TXT> UBRS,STRATH,SCHOL'),
('DISABLE_TYPE_QUEST', 6711, 0, '', '', 'Deprecated quest: <TXT> UBRS,STRATH,SCHOL - Repeatable'),
('DISABLE_TYPE_QUEST', 6841, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 6842, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 7069, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 7181, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 7202, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 7221, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 7222, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 7381, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 7382, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 7384, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 7561, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 7681, 0, '', '', 'Deprecated quest: Hunter test quest'),
('DISABLE_TYPE_QUEST', 7682, 0, '', '', 'Deprecated quest: Hunter test quest2'),
('DISABLE_TYPE_QUEST', 7741, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 7790, 0, '', '', 'Deprecated quest: REUSE'),
('DISABLE_TYPE_QUEST', 7797, 0, '', '', 'Deprecated quest: Dimensional Ripper - Everlook'),
('DISABLE_TYPE_QUEST', 7869, 0, '', '', 'Deprecated quest: test quest - do not use'),
('DISABLE_TYPE_QUEST', 7870, 0, '', '', 'Deprecated quest: test quest2 - do not use'),
('DISABLE_TYPE_QUEST', 7904, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 7906, 0, '', '', 'Deprecated quest: Darkmoon Cards - Beasts'),
('DISABLE_TYPE_QUEST', 7961, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 7962, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8002, 0, '', '', 'Deprecated quest: Silverwing Sentinels <NYI> <TXT>'),
('DISABLE_TYPE_QUEST', 8021, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8022, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8023, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8024, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8025, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8026, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8080, 0, '', '', 'Deprecated quest: Arathi Basin Resources!'),
('DISABLE_TYPE_QUEST', 8081, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8123, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8124, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8152, 0, '', '', 'Deprecated quest: REUSE'),
('DISABLE_TYPE_QUEST', 8154, 0, '', '', 'Deprecated quest: Arathi Basin Resources!'),
('DISABLE_TYPE_QUEST', 8155, 0, '', '', 'Deprecated quest: Arathi Basin Resources!'),
('DISABLE_TYPE_QUEST', 8156, 0, '', '', 'Deprecated quest: Arathi Basin Resources!'),
('DISABLE_TYPE_QUEST', 8157, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8158, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8159, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8160, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8161, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8162, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8163, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8164, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8165, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8226, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8230, 0, '', '', 'Deprecated quest: Collin\'s Test Quest'),
('DISABLE_TYPE_QUEST', 8237, 0, '', '', 'Deprecated quest: REUSE'),
('DISABLE_TYPE_QUEST', 8244, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 8245, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 8247, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 8248, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 8270, 0, '', '', 'Deprecated quest: test copy quest'),
('DISABLE_TYPE_QUEST', 8274, 0, '', '', 'Deprecated quest: Test Kill Quest'),
('DISABLE_TYPE_QUEST', 8297, 0, '', '', 'Deprecated quest: Arathi Basin Resources!'),
('DISABLE_TYPE_QUEST', 8298, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8299, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8300, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8337, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 8339, 0, '', '', 'Deprecated quest: Royalty of the Council <NYI> <TXT> UNUSED'),
('DISABLE_TYPE_QUEST', 8340, 0, '', '', 'Deprecated quest: Twilight Signet Ring <NYI> <TXT>'),
('DISABLE_TYPE_QUEST', 8384, 0, '', '', 'Deprecated quest: Claiming Arathi Basin'),
('DISABLE_TYPE_QUEST', 8386, 0, '', '', 'Deprecated quest: Fight for Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8388, 0, '', '', 'Deprecated quest: For Great Honor'),
('DISABLE_TYPE_QUEST', 8389, 0, '', '', 'Deprecated quest: Battle of Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8390, 0, '', '', 'Deprecated quest: Conquering Arathi Basin'),
('DISABLE_TYPE_QUEST', 8391, 0, '', '', 'Deprecated quest: Claiming Arathi Basin'),
('DISABLE_TYPE_QUEST', 8392, 0, '', '', 'Deprecated quest: Claiming Arathi Basin'),
('DISABLE_TYPE_QUEST', 8397, 0, '', '', 'Deprecated quest: Claiming Arathi Basin'),
('DISABLE_TYPE_QUEST', 8398, 0, '', '', 'Deprecated quest: Claiming Arathi Basin'),
('DISABLE_TYPE_QUEST', 8404, 0, '', '', 'Deprecated quest: Fight for Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8405, 0, '', '', 'Deprecated quest: Fight for Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8406, 0, '', '', 'Deprecated quest: Fight for Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8407, 0, '', '', 'Deprecated quest: Fight for Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8408, 0, '', '', 'Deprecated quest: Fight for Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8431, 0, '', '', 'Deprecated quest: Battle of Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8432, 0, '', '', 'Deprecated quest: Battle of Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8433, 0, '', '', 'Deprecated quest: Battle of Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8434, 0, '', '', 'Deprecated quest: Battle of Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8435, 0, '', '', 'Deprecated quest: Battle of Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8440, 0, '', '', 'Deprecated quest: Conquering Arathi Basin'),
('DISABLE_TYPE_QUEST', 8441, 0, '', '', 'Deprecated quest: Conquering Arathi Basin'),
('DISABLE_TYPE_QUEST', 8442, 0, '', '', 'Deprecated quest: Conquering Arathi Basin'),
('DISABLE_TYPE_QUEST', 8443, 0, '', '', 'Deprecated quest: Conquering Arathi Basin'),
('DISABLE_TYPE_QUEST', 8444, 0, '', '', 'Deprecated quest: <NYI> <TXT> gossip shade of ambermoon'),
('DISABLE_TYPE_QUEST', 8445, 0, '', '', 'Deprecated quest: <NYI> <TXT> gossip shade of ambermoon'),
('DISABLE_TYPE_QUEST', 8448, 0, '', '', 'Deprecated quest: <TXT> Mystery Reward'),
('DISABLE_TYPE_QUEST', 8449, 0, '', '', 'Deprecated quest: <TXT> Mystery Reward'),
('DISABLE_TYPE_QUEST', 8450, 0, '', '', 'Deprecated quest: <TXT> Mystery Reward'),
('DISABLE_TYPE_QUEST', 8451, 0, '', '', 'Deprecated quest: <TXT> Mystery Reward'),
('DISABLE_TYPE_QUEST', 8452, 0, '', '', 'Deprecated quest: <TXT> Mystery Reward'),
('DISABLE_TYPE_QUEST', 8453, 0, '', '', 'Deprecated quest: <TXT> Mystery Reward'),
('DISABLE_TYPE_QUEST', 8454, 0, '', '', 'Deprecated quest: <TXT> Mystery Reward'),
('DISABLE_TYPE_QUEST', 8458, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 8459, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 8530, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8531, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8567, 0, '', '', 'Deprecated quest: Past Victories in Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8568, 0, '', '', 'Deprecated quest: Past Victories in Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8569, 0, '', '', 'Deprecated quest: Past Efforts in Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8570, 0, '', '', 'Deprecated quest: Past Efforts in Warsong Gulch'),
('DISABLE_TYPE_QUEST', 8571, 0, '', '', 'Deprecated quest: <UNUSED> Armor Kits'),
('DISABLE_TYPE_QUEST', 8617, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8618, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8869, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 8971, 0, '', '', 'Deprecated quest: REUSE'),
('DISABLE_TYPE_QUEST', 8972, 0, '', '', 'Deprecated quest: REUSE'),
('DISABLE_TYPE_QUEST', 8973, 0, '', '', 'Deprecated quest: REUSE'),
('DISABLE_TYPE_QUEST', 8974, 0, '', '', 'Deprecated quest: REUSE'),
('DISABLE_TYPE_QUEST', 8975, 0, '', '', 'Deprecated quest: REUSE'),
('DISABLE_TYPE_QUEST', 8976, 0, '', '', 'Deprecated quest: REUSE'),
('DISABLE_TYPE_QUEST', 9031, 0, '', '', 'Deprecated quest: <TXT>Anthion\'s Parting Words'),
('DISABLE_TYPE_QUEST', 9034, 0, '', '', 'Deprecated quest: Dreadnaught Breastplate'),
('DISABLE_TYPE_QUEST', 9036, 0, '', '', 'Deprecated quest: Dreadnaught Legplates'),
('DISABLE_TYPE_QUEST', 9037, 0, '', '', 'Deprecated quest: Dreadnaught Helmet'),
('DISABLE_TYPE_QUEST', 9038, 0, '', '', 'Deprecated quest: Dreadnaught Pauldrons'),
('DISABLE_TYPE_QUEST', 9039, 0, '', '', 'Deprecated quest: Dreadnaught Sabatons'),
('DISABLE_TYPE_QUEST', 9040, 0, '', '', 'Deprecated quest: Dreadnaught Gauntlets'),
('DISABLE_TYPE_QUEST', 9041, 0, '', '', 'Deprecated quest: Dreadnaught Waistguard'),
('DISABLE_TYPE_QUEST', 9042, 0, '', '', 'Deprecated quest: Dreadnaught Bracers'),
('DISABLE_TYPE_QUEST', 9043, 0, '', '', 'Deprecated quest: Redemption Tunic'),
('DISABLE_TYPE_QUEST', 9044, 0, '', '', 'Deprecated quest: Redemption Legguards'),
('DISABLE_TYPE_QUEST', 9046, 0, '', '', 'Deprecated quest: Redemption Spaulders'),
('DISABLE_TYPE_QUEST', 9047, 0, '', '', 'Deprecated quest: Redemption Boots'),
('DISABLE_TYPE_QUEST', 9048, 0, '', '', 'Deprecated quest: Redemption Handguards'),
('DISABLE_TYPE_QUEST', 9049, 0, '', '', 'Deprecated quest: Redemption Girdle'),
('DISABLE_TYPE_QUEST', 9050, 0, '', '', 'Deprecated quest: Redemption Wristguards'),
('DISABLE_TYPE_QUEST', 9054, 0, '', '', 'Deprecated quest: Cryptstalker Tunic'),
('DISABLE_TYPE_QUEST', 9055, 0, '', '', 'Deprecated quest: Cryptstalker Legguards'),
('DISABLE_TYPE_QUEST', 9056, 0, '', '', 'Deprecated quest: Cryptstalker Headpiece'),
('DISABLE_TYPE_QUEST', 9057, 0, '', '', 'Deprecated quest: Cryptstalker Spaulders'),
('DISABLE_TYPE_QUEST', 9058, 0, '', '', 'Deprecated quest: Cryptstalker Boots'),
('DISABLE_TYPE_QUEST', 9059, 0, '', '', 'Deprecated quest: Cryptstalker Handguards'),
('DISABLE_TYPE_QUEST', 9060, 0, '', '', 'Deprecated quest: Cryptstalker Girdle'),
('DISABLE_TYPE_QUEST', 9061, 0, '', '', 'Deprecated quest: Cryptstalker Wristguards'),
('DISABLE_TYPE_QUEST', 9068, 0, '', '', 'Deprecated quest: Earthshatter Tunic'),
('DISABLE_TYPE_QUEST', 9069, 0, '', '', 'Deprecated quest: Earthshatter Legguards');

INSERT INTO `vw_disables_with_labels` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES
('DISABLE_TYPE_QUEST', 9070, 0, '', '', 'Deprecated quest: Earthshatter Headpiece'),
('DISABLE_TYPE_QUEST', 9071, 0, '', '', 'Deprecated quest: Earthshatter Spaulders'),
('DISABLE_TYPE_QUEST', 9072, 0, '', '', 'Deprecated quest: Earthshatter Boots'),
('DISABLE_TYPE_QUEST', 9073, 0, '', '', 'Deprecated quest: Earthshatter Handguards'),
('DISABLE_TYPE_QUEST', 9074, 0, '', '', 'Deprecated quest: Earthshatter Girdle'),
('DISABLE_TYPE_QUEST', 9075, 0, '', '', 'Deprecated quest: Earthshatter Wristguards'),
('DISABLE_TYPE_QUEST', 9077, 0, '', '', 'Deprecated quest: Bonescythe Breastplate'),
('DISABLE_TYPE_QUEST', 9078, 0, '', '', 'Deprecated quest: Bonescythe Legplates'),
('DISABLE_TYPE_QUEST', 9079, 0, '', '', 'Deprecated quest: Bonescythe Helmet'),
('DISABLE_TYPE_QUEST', 9080, 0, '', '', 'Deprecated quest: Bonescythe Pauldrons'),
('DISABLE_TYPE_QUEST', 9081, 0, '', '', 'Deprecated quest: Bonescythe Sabatons'),
('DISABLE_TYPE_QUEST', 9082, 0, '', '', 'Deprecated quest: Bonescythe Gauntlets'),
('DISABLE_TYPE_QUEST', 9083, 0, '', '', 'Deprecated quest: Bonescythe Waistguard'),
('DISABLE_TYPE_QUEST', 9084, 0, '', '', 'Deprecated quest: Bonescythe Bracers'),
('DISABLE_TYPE_QUEST', 9086, 0, '', '', 'Deprecated quest: Dreamwalker Tunic'),
('DISABLE_TYPE_QUEST', 9087, 0, '', '', 'Deprecated quest: Dreamwalker Legguards'),
('DISABLE_TYPE_QUEST', 9088, 0, '', '', 'Deprecated quest: Dreamwalker Headpiece'),
('DISABLE_TYPE_QUEST', 9089, 0, '', '', 'Deprecated quest: Dreamwalker Spaulders'),
('DISABLE_TYPE_QUEST', 9090, 0, '', '', 'Deprecated quest: Dreamwalker Boots'),
('DISABLE_TYPE_QUEST', 9091, 0, '', '', 'Deprecated quest: Dreamwalker Handguards'),
('DISABLE_TYPE_QUEST', 9092, 0, '', '', 'Deprecated quest: Dreamwalker Girdle'),
('DISABLE_TYPE_QUEST', 9093, 0, '', '', 'Deprecated quest: Dreamwalker Wristguards'),
('DISABLE_TYPE_QUEST', 9095, 0, '', '', 'Deprecated quest: Frostfire Robe'),
('DISABLE_TYPE_QUEST', 9096, 0, '', '', 'Deprecated quest: Frostfire Leggings'),
('DISABLE_TYPE_QUEST', 9097, 0, '', '', 'Deprecated quest: Frostfire Circlet'),
('DISABLE_TYPE_QUEST', 9098, 0, '', '', 'Deprecated quest: Frostfire Shoulderpads'),
('DISABLE_TYPE_QUEST', 9099, 0, '', '', 'Deprecated quest: Frostfire Sandals'),
('DISABLE_TYPE_QUEST', 9100, 0, '', '', 'Deprecated quest: Frostfire Gloves'),
('DISABLE_TYPE_QUEST', 9101, 0, '', '', 'Deprecated quest: Frostfire Belt'),
('DISABLE_TYPE_QUEST', 9102, 0, '', '', 'Deprecated quest: Frostfire Bindings'),
('DISABLE_TYPE_QUEST', 9103, 0, '', '', 'Deprecated quest: Plagueheart Robe'),
('DISABLE_TYPE_QUEST', 9104, 0, '', '', 'Deprecated quest: Plagueheart Leggings'),
('DISABLE_TYPE_QUEST', 9105, 0, '', '', 'Deprecated quest: Plagueheart Circlet'),
('DISABLE_TYPE_QUEST', 9106, 0, '', '', 'Deprecated quest: Plagueheart Shoulderpads'),
('DISABLE_TYPE_QUEST', 9107, 0, '', '', 'Deprecated quest: Plagueheart Sandals'),
('DISABLE_TYPE_QUEST', 9108, 0, '', '', 'Deprecated quest: Plagueheart Gloves'),
('DISABLE_TYPE_QUEST', 9109, 0, '', '', 'Deprecated quest: Plagueheart Belt'),
('DISABLE_TYPE_QUEST', 9110, 0, '', '', 'Deprecated quest: Plagueheart Bindings'),
('DISABLE_TYPE_QUEST', 9111, 0, '', '', 'Deprecated quest: Robe of Faith'),
('DISABLE_TYPE_QUEST', 9112, 0, '', '', 'Deprecated quest: Leggings of Faith'),
('DISABLE_TYPE_QUEST', 9113, 0, '', '', 'Deprecated quest: Circlet of Faith'),
('DISABLE_TYPE_QUEST', 9114, 0, '', '', 'Deprecated quest: Shoulderpads of Faith'),
('DISABLE_TYPE_QUEST', 9115, 0, '', '', 'Deprecated quest: Sandals of Faith'),
('DISABLE_TYPE_QUEST', 9116, 0, '', '', 'Deprecated quest: Gloves of Faith'),
('DISABLE_TYPE_QUEST', 9117, 0, '', '', 'Deprecated quest: Belt of Faith'),
('DISABLE_TYPE_QUEST', 9118, 0, '', '', 'Deprecated quest: Bindings of Faith'),
('DISABLE_TYPE_QUEST', 9168, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9231, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9273, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9284, 0, '', '', 'Deprecated quest: Aldor Faction Test'),
('DISABLE_TYPE_QUEST', 9285, 0, '', '', 'Deprecated quest: Consortium Faction Test'),
('DISABLE_TYPE_QUEST', 9286, 0, '', '', 'Deprecated quest: Scryers Faction Test'),
('DISABLE_TYPE_QUEST', 9296, 0, '', '', 'Deprecated quest: reuse'),
('DISABLE_TYPE_QUEST', 9297, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9298, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9306, 0, '', '', 'Deprecated quest: <DEPRECATED>Speak with Vindicator Aldar'),
('DISABLE_TYPE_QUEST', 9307, 0, '', '', 'Deprecated quest: <DEPRECATED>Compassion'),
('DISABLE_TYPE_QUEST', 9308, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9316, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9319, 0, '0', '0', 'Quest: A Light in Dark Places, removed in patch 2.4.0'),
('DISABLE_TYPE_QUEST', 9322, 0, '0', '0', 'Disable quest Wild Fires in Kalimdor /Deprecated after 2008/'),
('DISABLE_TYPE_QUEST', 9323, 0, '0', '0', 'Disable quest Wild Fires in Eastern Kingdoms /Deprecated after 2008/'),
('DISABLE_TYPE_QUEST', 9347, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9350, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9353, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9354, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9367, 0, '0', '0', 'Quest: The Festival of Fire {A}, removed in patch 2.4.0'),
('DISABLE_TYPE_QUEST', 9368, 0, '0', '0', 'Quest: The Festival of Fire {H}, removed in patch 2.4.0'),
('DISABLE_TYPE_QUEST', 9378, 0, '', '', 'Deprecated quest: DND FLAG The Dread Citadel - Naxxramas'),
('DISABLE_TYPE_QUEST', 9379, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9380, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9384, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9386, 0, '0', '0', 'Quest: A Light in Dark Places {Daily}, removed in patch 2.4.0'),
('DISABLE_TYPE_QUEST', 9388, 0, '0', '0', 'Disable quest Flickering Flames in Kalimdor /Deprecated after 2008/'),
('DISABLE_TYPE_QUEST', 9389, 0, '0', '0', 'Disable quest Flickering Flames in the Eastern Kingdoms /Deprecated after 2008/'),
('DISABLE_TYPE_QUEST', 9411, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9412, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9413, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9414, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9445, 0, '', '', 'Deprecated quest: <NYI><TXT>Placeholder: A Worthy Offering'),
('DISABLE_TYPE_QUEST', 9458, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9459, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9477, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9478, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9479, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9480, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9481, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9482, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9497, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9507, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9546, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9577, 0, '', '', 'Deprecated quest: DAILY TEST QUEST (PVP)'),
('DISABLE_TYPE_QUEST', 9583, 0, '', '', 'Deprecated quest: Omar\'s Test Quest'),
('DISABLE_TYPE_QUEST', 9596, 0, '', '', 'Deprecated quest: <DEPRECATED>Control'),
('DISABLE_TYPE_QUEST', 9597, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 9599, 0, '', '', 'Deprecated quest: <UNUSED>'),
('DISABLE_TYPE_QUEST', 9611, 0, '', '', 'Deprecated quest: Azuremyst: aa - A - Quest Flag 000'),
('DISABLE_TYPE_QUEST', 9613, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9614, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9615, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9650, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9651, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9652, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9653, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9654, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9655, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9656, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9657, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9658, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9659, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9660, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9661, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9662, 0, '', '', 'Deprecated quest:Deprecated: Keanna\'s Freedom'),
('DISABLE_TYPE_QUEST', 9679, 0, '', '', 'Deprecated quest: <NYI>Return to Knight-Lord Bloodvalor'),
('DISABLE_TYPE_QUEST', 9695, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9745, 0, '', '', 'Deprecated quest: <DEPRECATED>Suppressing the Flame'),
('DISABLE_TYPE_QUEST', 9750, 0, '', '', 'Deprecated quest: UNUSED Urgent Delivery'),
('DISABLE_TYPE_QUEST', 9754, 0, '', '', 'Deprecated quest: '),
('DISABLE_TYPE_QUEST', 9755, 0, '', '', 'Deprecated quest: '),
('DISABLE_TYPE_QUEST', 9767, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9768, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 9880, 0, '', '', 'Deprecated quest: Hellfire Penninsula: -pn - A - ToWoW - Hellfire Turnin Cap'),
('DISABLE_TYPE_QUEST', 9881, 0, '', '', 'Deprecated quest: Hellfire Penninsula: -pn - H - ToWoW - Hellfire Turnin Cap'),
('DISABLE_TYPE_QUEST', 9908, 0, '', '', 'Deprecated quest: Hellfire Penninsula: -pn - A - ToWoW - Hellfire Turnin'),
('DISABLE_TYPE_QUEST', 9909, 0, '', '', 'Deprecated quest: Hellfire Penninsula: -pn - H - ToWoW - Hellfire Turnin'),
('DISABLE_TYPE_QUEST', 9949, 0, '', '', 'Deprecated quest: A Bird\'s-Eye View'),
('DISABLE_TYPE_QUEST', 9950, 0, '', '', 'Deprecated quest: A Bird\'s-Eye View'),
('DISABLE_TYPE_QUEST', 10083, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 10088, 0, '', '', 'Deprecated quest: When This Mine\'s a-Rockin\''),
('DISABLE_TYPE_QUEST', 10090, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 10145, 0, '', '', 'Deprecated quest: Mission: Sever the Tie UNUSED'),
('DISABLE_TYPE_QUEST', 10181, 0, '', '', 'Deprecated quest: Collector\'s Edition: -pn - E - FLAG'),
('DISABLE_TYPE_QUEST', 10207, 0, '', '', 'Deprecated quest: Forward Base: Reaver\'s Fall REUSE'),
('DISABLE_TYPE_QUEST', 10214, 0, '', '', 'Deprecated quest: When This Mine\'s a-Rockin\''),
('DISABLE_TYPE_QUEST', 10215, 0, '', '', 'Deprecated quest: '),
('DISABLE_TYPE_QUEST', 10370, 0, '', '', 'Deprecated quest: Nazgrel\'s Command <TXT>'),
('DISABLE_TYPE_QUEST', 10376, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 10377, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 10378, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 10379, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 10402, 0, '', '', 'Deprecated quest: <TXT>'),
('DISABLE_TYPE_QUEST', 10452, 0, '', '', 'Deprecated quest:DON\'T USE [PH] Fel Orc 1'),
('DISABLE_TYPE_QUEST', 10453, 0, '', '', 'Deprecated quest:DON\'T USE [PH] Fel Orc bread'),
('DISABLE_TYPE_QUEST', 10454, 0, '', '', 'Deprecated quest: FLAG - OFF THE RAILS'),
('DISABLE_TYPE_QUEST', 10549, 0, '', '', 'Deprecated quest: REUSE'),
('DISABLE_TYPE_QUEST', 10616, 0, '', '', 'Deprecated quest: <nyi>Breadcrumb'),
('DISABLE_TYPE_QUEST', 10631, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 10716, 0, '', '', 'Deprecated quest Test Flight: Raven\'s Wood'),
('DISABLE_TYPE_QUEST', 10743, 0, '', '', 'Deprecated quest: [DEPRECATED]<txt>Hero of the Mok\'Nathal'),
('DISABLE_TYPE_QUEST', 10746, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 10787, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 10871, 0, '', '', 'Deprecated quest - Ally of the Netherwing (first version - when it was for alliance only, reworked after 3.3.0)'),
('DISABLE_TYPE_QUEST', 10890, 0, '', '', 'Deprecated quest: [UNUSED] <NYI> '),
('DISABLE_TYPE_QUEST', 10960, 0, '', '', 'Deprecated quest: When I grow up...'),
('DISABLE_TYPE_QUEST', 11088, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11121, 0, '', '', 'Deprecated quest: DAILY TEST QUEST (RAID)'),
('DISABLE_TYPE_QUEST', 11125, 0, '', '', 'Deprecated quest:[PH] New Hinterlands Quest'),
('DISABLE_TYPE_QUEST', 11127, 0, '', '', 'Deprecated quest: <NYI>Thunderbrew Secrets'),
('DISABLE_TYPE_QUEST', 11179, 0, '', '', 'Deprecated quest:[Temporarily Deprecated Awaiting a New Mob]Finlay Is Gutless'),
('DISABLE_TYPE_QUEST', 11197, 0, '', '', 'Deprecated quest: ZZOLD Upper Deck Promo - Ghost Wolf Mount OLD'),
('DISABLE_TYPE_QUEST', 11226, 0, '', '', 'Deprecated quest: Upper Deck Promo - Spectral Tiger Mount'),
('DISABLE_TYPE_QUEST', 11320, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11334, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11335, 0, '', '', 'Deprecated quest: Call to Arms: Arathi Basin'),
('DISABLE_TYPE_QUEST', 11336, 0, '', '', 'Deprecated quest: Call to Arms: Alterac Valley'),
('DISABLE_TYPE_QUEST', 11337, 0, '', '', 'Deprecated quest: Call to Arms: Eye of the Storm'),
('DISABLE_TYPE_QUEST', 11338, 0, '', '', 'Deprecated quest: Call to Arms: Warsong Gulch'),
('DISABLE_TYPE_QUEST', 11339, 0, '', '', 'Deprecated quest: Call to Arms: Arathi Basin'),
('DISABLE_TYPE_QUEST', 11340, 0, '', '', 'Deprecated quest: Call to Arms: Alterac Valley'),
('DISABLE_TYPE_QUEST', 11341, 0, '', '', 'Deprecated quest: Call to Arms: Eye of the Storm'),
('DISABLE_TYPE_QUEST', 11342, 0, '', '', 'Deprecated quest: Call to Arms: Warsong Gulch'),
('DISABLE_TYPE_QUEST', 11345, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11347, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11425, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11435, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11437, 0, '', '', 'Deprecated quest:[PH] Beer Garden A'),
('DISABLE_TYPE_QUEST', 11438, 0, '', '', 'Deprecated quest:[PH] Beer Garden B'),
('DISABLE_TYPE_QUEST', 11444, 0, '', '', 'Deprecated quest:[PH] Beer Garden A'),
('DISABLE_TYPE_QUEST', 11445, 0, '', '', 'Deprecated quest:[PH] Beer Garden B'),
('DISABLE_TYPE_QUEST', 11461, 0, '', '', 'Deprecated quest:DEPRECATED'),
('DISABLE_TYPE_QUEST', 11462, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11493, 0, '', '', 'Deprecated quest: UNUSED'),
('DISABLE_TYPE_QUEST', 11522, 0, '', '', 'Deprecated quest: '),
('DISABLE_TYPE_QUEST', 11551, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11552, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11553, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11577, 0, '', '', 'Deprecated quest: WoW Collector\'s Edition: - DEM - E - FLAG'),
('DISABLE_TYPE_QUEST', 11578, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11579, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11588, 0, '', '', 'Deprecated quest: REUSE'),
('DISABLE_TYPE_QUEST', 11589, 0, '', '', 'Deprecated quest: REUSE'),
('DISABLE_TYPE_QUEST', 11874, 0, '', '', 'Deprecated quest: Upper Deck Promo - Rocket Mount'),
('DISABLE_TYPE_QUEST', 11934, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11937, 0, '', '', 'Deprecated quest: FLAG - all torch return quests are complete'),
('DISABLE_TYPE_QUEST', 11974, 0, '', '', 'Deprecated quest:[ph] Now, When I Grow Up...'),
('DISABLE_TYPE_QUEST', 11987, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11992, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 11994, 0, '', '', 'Deprecated quest: Juno\'s Flag Tester'),
('DISABLE_TYPE_QUEST', 11997, 0, '', '', 'Deprecated quest: REUSE'),
('DISABLE_TYPE_QUEST', 12001, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 12015, 0, '', '', 'Deprecated quest: Test Quest for Craig'),
('DISABLE_TYPE_QUEST', 12018, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 12024, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 12025, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 12087, 0, '', '', 'Deprecated quest:A Little Help Here? DEPRECATED'),
('DISABLE_TYPE_QUEST', 12103, 0, '', '', 'Deprecated quest:DEPRECATED'),
('DISABLE_TYPE_QUEST', 12108, 0, '', '', 'Deprecated quest:DEPRECATED'),
('DISABLE_TYPE_QUEST', 12156, 0, '', '', 'Deprecated quest:DEPRECAED'),
('DISABLE_TYPE_QUEST', 12179, 0, '', '', 'Deprecated quest:Specialization 1 [PH]'),
('DISABLE_TYPE_QUEST', 12228, 0, '', '', 'Deprecated quest:Reacquiring the Magic [PH]'),
('DISABLE_TYPE_QUEST', 12233, 0, '', '', 'Deprecated quest:[Depricated]Sewing Your Seed'),
('DISABLE_TYPE_QUEST', 12313, 0, '', '', 'Deprecated quest: UNUSED Save Brewfest!'),
('DISABLE_TYPE_QUEST', 12426, 0, '', '', 'Deprecated quest:DEPRECATED'),
('DISABLE_TYPE_QUEST', 12445, 0, '', '', 'Deprecated quest: '),
('DISABLE_TYPE_QUEST', 12493, 0, '', '', 'Deprecated quest: PvP Test'),
('DISABLE_TYPE_QUEST', 12590, 0, '', '', 'Deprecated quest:Blahblah[PH]'),
('DISABLE_TYPE_QUEST', 12600, 0, '', '', 'Deprecated quest: Upper Deck Promo - Bear Mount'),
('DISABLE_TYPE_QUEST', 12626, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 12682, 0, '', '', 'Deprecated quest:Uncharted Territory (DEPRECATED)'),
('DISABLE_TYPE_QUEST', 12731, 0, '', '', 'Deprecated quest: '),
('DISABLE_TYPE_QUEST', 12752, 0, '0', '0', 'Disable quest from Scourge Invasion for undead'),
('DISABLE_TYPE_QUEST', 12753, 0, '0', '0', 'Disable quest from Scourge Invasion for Dwarves'),
('DISABLE_TYPE_QUEST', 12764, 0, '', '', 'Deprecated quest:The Secret to Kungaloosh (DEPRECATED)'),
('DISABLE_TYPE_QUEST', 12765, 0, '', '', 'Deprecated quest:Kungaloosh (DEPRECATED)'),
('DISABLE_TYPE_QUEST', 12771, 0, '0', '0', 'Disable quest from Scourge Invasion for Dwarves'),
('DISABLE_TYPE_QUEST', 12772, 0, '0', '0', 'Disable quest from Scourge Invasion for Night Elves'),
('DISABLE_TYPE_QUEST', 12773, 0, '0', '0', 'Disable quest from Scourge Invasion for Night Elves'),
('DISABLE_TYPE_QUEST', 12774, 0, '0', '0', 'Disable quest from Scourge Invasion for Human'),
('DISABLE_TYPE_QUEST', 12775, 0, '0', '0', 'Disable quest from Scourge Invasion for Human'),
('DISABLE_TYPE_QUEST', 12776, 0, '0', '0', 'Disable quest from Scourge Invasion for Draenei'),
('DISABLE_TYPE_QUEST', 12777, 0, '0', '0', 'Disable quest from Scourge Invasion for Draenei'),
('DISABLE_TYPE_QUEST', 12782, 0, '0', '0', 'Disable quest from Scourge Invasion for Blood Elves'),
('DISABLE_TYPE_QUEST', 12783, 0, '0', '0', 'Disable quest from Scourge Invasion for Orcs'),
('DISABLE_TYPE_QUEST', 12784, 0, '0', '0', 'Disable quest from Scourge Invasion for Tauren'),
('DISABLE_TYPE_QUEST', 12785, 0, '0', '0', 'Disable quest from Scourge Invasion for Trolls'),
('DISABLE_TYPE_QUEST', 12786, 0, '0', '0', 'Disable quest from Scourge Invasion for Tauren'),
('DISABLE_TYPE_QUEST', 12787, 0, '0', '0', 'Disable quest from Scourge Invasion for undead'),
('DISABLE_TYPE_QUEST', 12788, 0, '0', '0', 'Disable quest from Scourge Invasion for Blood Elves'),
('DISABLE_TYPE_QUEST', 12808, 0, '0', '0', 'Disable quest from Scourge Invasion for Gnomes'),
('DISABLE_TYPE_QUEST', 12809, 0, '0', '0', 'Disable quest from Scourge Invasion for Gnomes'),
('DISABLE_TYPE_QUEST', 12811, 0, '0', '0', 'Disable quest from Scourge Invasion for Trolls'),
('DISABLE_TYPE_QUEST', 12812, 0, '0', '0', 'Disable quest from Scourge Invasion for Orcs'),
('DISABLE_TYPE_QUEST', 12911, 0, '', '', 'Deprecated quest: Kill Credit Test'),
('DISABLE_TYPE_QUEST', 12923, 0, '', '', 'Deprecated quest: '),
('DISABLE_TYPE_QUEST', 13123, 0, '', '', 'Deprecated quest: WotLK Collector\'s Edition: - DEM - E - FLAG'),
('DISABLE_TYPE_QUEST', 13210, 0, '', '', 'Deprecated quest: Blizzard Account: - DEM - E - FLAG'),
('DISABLE_TYPE_QUEST', 13303, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 13317, 0, '', '', 'Deprecated quest: ----'),
('DISABLE_TYPE_QUEST', 13405, 0, '', '', 'Deprecated quest: Call to Arms: Strand of the Ancients'),
('DISABLE_TYPE_QUEST', 13407, 0, '', '', 'Deprecated quest: Call to Arms: Strand of the Ancients'),
('DISABLE_TYPE_QUEST', 13427, 0, '', '', 'Deprecated quest: Call to Arms: Alterac Valley'),
('DISABLE_TYPE_QUEST', 13428, 0, '', '', 'Deprecated quest: Call to Arms: Alterac Valley'),
('DISABLE_TYPE_QUEST', 13475, 0, '', '', 'Deprecated quest: For Great Honor'),
('DISABLE_TYPE_QUEST', 13541, 0, '', '', 'Deprecated quest: '),
('DISABLE_TYPE_QUEST', 13649, 0, '', '', 'Deprecated quest: Justin\'s Fun Test'),
('DISABLE_TYPE_QUEST', 13827, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 13840, 0, '', '', 'Deprecated quest: REUSE'),
('DISABLE_TYPE_QUEST', 13990, 0, '', '', 'Deprecated quest: Upper Deck Promo - Chicken Mount'),
('DISABLE_TYPE_QUEST', 14106, 0, '', '', 'Deprecated quest: Na Kada\'s Quest Test'),
('DISABLE_TYPE_QUEST', 14119, 0, '', '', 'Deprecated quest:Blank [PH]'),
('DISABLE_TYPE_QUEST', 14147, 0, '', '', 'Deprecated quest:Blank [PH]'),
('DISABLE_TYPE_QUEST', 14148, 0, '', '', 'Deprecated quest:Blank [PH]'),
('DISABLE_TYPE_QUEST', 14149, 0, '', '', 'Deprecated quest:Blank [PH]'),
('DISABLE_TYPE_QUEST', 14150, 0, '', '', 'Deprecated quest:Blank [PH]'),
('DISABLE_TYPE_QUEST', 14163, 0, '', '', 'Deprecated quest: Call to Arms: Isle of Conquest'),
('DISABLE_TYPE_QUEST', 14164, 0, '', '', 'Deprecated quest: Call to Arms: Isle of Conquest'),
('DISABLE_TYPE_QUEST', 14178, 0, '', '', 'Deprecated quest: Call to Arms: Arathi Basin'),
('DISABLE_TYPE_QUEST', 14179, 0, '', '', 'Deprecated quest: Call to Arms: Eye of the Storm'),
('DISABLE_TYPE_QUEST', 14180, 0, '', '', 'Deprecated quest: Call to Arms: Warsong Gulch'),
('DISABLE_TYPE_QUEST', 14181, 0, '', '', 'Deprecated quest: Call to Arms: Arathi Basin'),
('DISABLE_TYPE_QUEST', 14182, 0, '', '', 'Deprecated quest: Call to Arms: Eye of the Storm'),
('DISABLE_TYPE_QUEST', 14183, 0, '', '', 'Deprecated quest: Call to Arms: Warsong Gulch'),
('DISABLE_TYPE_QUEST', 14349, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 14441, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 24216, 0, '', '', 'Deprecated quest: Call to Arms: Warsong Gulch'),
('DISABLE_TYPE_QUEST', 24217, 0, '', '', 'Deprecated quest: Call to Arms: Warsong Gulch'),
('DISABLE_TYPE_QUEST', 24218, 0, '', '', 'Deprecated quest: Call to Arms: Warsong Gulch'),
('DISABLE_TYPE_QUEST', 24219, 0, '', '', 'Deprecated quest: Call to Arms: Warsong Gulch'),
('DISABLE_TYPE_QUEST', 24220, 0, '', '', 'Deprecated quest: Call to Arms: Arathi Basin'),
('DISABLE_TYPE_QUEST', 24221, 0, '', '', 'Deprecated quest: Call to Arms: Arathi Basin'),
('DISABLE_TYPE_QUEST', 24222, 0, '', '', 'Deprecated quest:Call to Arms: Eye of the Storm DEPRECATED'),
('DISABLE_TYPE_QUEST', 24223, 0, '', '', 'Deprecated quest: Call to Arms: Arathi Basin'),
('DISABLE_TYPE_QUEST', 24224, 0, '', '', 'Deprecated quest: Call to Arms: Warsong Gulch'),
('DISABLE_TYPE_QUEST', 24225, 0, '', '', 'Deprecated quest: Call to Arms: Warsong Gulch'),
('DISABLE_TYPE_QUEST', 24226, 0, '', '', 'Deprecated quest: Call to Arms: Arathi Basin'),
('DISABLE_TYPE_QUEST', 24227, 0, '', '', 'Deprecated quest:DEPRECATED'),
('DISABLE_TYPE_QUEST', 24426, 0, '', '', 'Deprecated quest: Call to Arms: Alterac Valley'),
('DISABLE_TYPE_QUEST', 24427, 0, '', '', 'Deprecated quest: Call to Arms: Alterac Valley'),
('DISABLE_TYPE_QUEST', 24661, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 24746, 0, '', '', 'Deprecated quest'),
('DISABLE_TYPE_QUEST', 24797, 0, '', '', 'Deprecated quest: REUSE'),
('DISABLE_TYPE_BATTLEGROUND', 10, 0, '', '', ''),
('DISABLE_TYPE_BATTLEGROUND', 11, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 4959, 0, '', '', '2v2 Arena Honorable Kills'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 4960, 0, '', '', '3v3 Arena Honorable Kills'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 4961, 0, '', '', '5v5 Arena Honorable Kills'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 7326, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 7327, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 7704, 0, '', '', 'Vehicular Gnomeslaughter'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 7705, 0, '', '', 'Vehicular Gnomeslaughter'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 7706, 0, '', '', 'Vehicular Gnomeslaughter'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 7707, 0, '', '', 'Vehicular Gnomeslaughter'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 7708, 0, '', '', 'Vehicular Gnomeslaughter'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 8839, 0, '', '', 'Arena Honorable Kills'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 9161, 0, '', '', 'Arena Honorable Kills'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 9162, 0, '', '', 'Arena Honorable Kills'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 9163, 0, '', '', 'Arena Honorable Kills'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 9164, 0, '', '', 'Arena Honorable Kills'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 10090, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 10091, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 10095, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 10099, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 10133, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 10285, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 10286, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 10290, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 10422, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 10423, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 10424, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 10425, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 10800, 0, '0', '0', 'Siffed (10 player) - Duplicate'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 10801, 0, '0', '0', 'Siffed (25 player) - Duplicate'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 11238, 0, '', '', 'Achievement: Jade Tiger'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 11491, 0, '', '', 'Isle of Conquest All-Star'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 12339, 0, '', '', 'A Tribute to Skill (25 player)'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 12340, 0, '', '', 'A Tribute to Skill (25 player)'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 12342, 0, '', '', 'A Tribute to Mad Skill (25 player)'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 12345, 0, '', '', 'A Tribute to Skill (10 player)'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 12346, 0, '', '', 'A Tribute to Skill (10 player)'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 12348, 0, '', '', 'A Tribute to Mad Skill (10 player)'),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 12681, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 12801, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13185, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13186, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13189, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13190, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13191, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13192, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13193, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13195, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13196, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13197, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13200, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13201, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13202, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13203, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13204, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13206, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13393, 0, '', '', ''),
('DISABLE_TYPE_ACHIEVEMENT_CRITERIA', 13394, 0, '', '', ''),
('DISABLE_TYPE_MMAP', 649, 0, '', '', 'Disable mmaps - Trial of the Crusader'),
('DISABLE_TYPE_MMAP', 650, 0, '', '', 'Disable mmaps - Trial of the Champion');

-- 852 ligne(s)
SET FOREIGN_KEY_CHECKS = 1;
