-- Export de la table `warchief_command_flyers`
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `warchief_command_flyers`;
CREATE TABLE `warchief_command_flyers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Identifiant unique du dépliant',
  `faction` tinyint(4) NOT NULL DEFAULT 0 COMMENT '0 = Horde, 1 = Alliance',
  `sort_order` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'Ordre d affichage (0 = premier)',
  `title` varchar(64) NOT NULL COMMENT 'Titre affiché sur le bandeau parchemin',
  `description` text NOT NULL COMMENT 'Texte descriptif du dépliant',
  `button_label` varchar(32) NOT NULL COMMENT 'Texte du bouton (ex: Aller à Uldum)',
  `card_image` varchar(128) NOT NULL COMMENT 'Chemin BLP de l image de la carte',
  `quest_id` int(10) unsigned NOT NULL COMMENT 'ID de la quête à donner au joueur',
  `map_id` int(10) unsigned NOT NULL COMMENT 'ID de la map de destination (Teleport)',
  `pos_x` float NOT NULL DEFAULT 0 COMMENT 'Coordonnée X de téléportation',
  `pos_y` float NOT NULL DEFAULT 0 COMMENT 'Coordonnée Y de téléportation',
  `pos_z` float NOT NULL DEFAULT 0 COMMENT 'Coordonnée Z de téléportation',
  `orientation` float NOT NULL DEFAULT 0 COMMENT 'Orientation du joueur après téléportation',
  `teleport_msg` varchar(128) NOT NULL COMMENT 'Message broadcast après téléportation',
  `enabled` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1 = actif, 0 = désactivé',
  `title_en` varchar(64) DEFAULT NULL COMMENT 'Titre (anglais)',
  `description_en` text DEFAULT NULL COMMENT 'Texte descriptif (anglais)',
  `button_label_en` varchar(32) DEFAULT NULL COMMENT 'Texte du bouton (anglais)',
  `teleport_msg_en` varchar(128) DEFAULT NULL COMMENT 'Message broadcast après téléportation (anglais)',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_faction_sort` (`faction`,`sort_order`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='Dépliant dynamique du tableau du chef de guerre';

INSERT INTO `warchief_command_flyers` (`id`, `faction`, `sort_order`, `title`, `description`, `button_label`, `card_image`, `quest_id`, `map_id`, `pos_x`, `pos_y`, `pos_z`, `orientation`, `teleport_msg`, `enabled`, `title_en`, `description_en`, `button_label_en`, `teleport_msg_en`) VALUES
(1, 1, 0, 'Uldum', 'Les anciennes terres d\'Uldum ont été mises au jour, livrant leurs trésors ancestraux et la technologie des Titans aux armées de l\'Alliance et de la Horde.\n\nRejoignez la caravane d\'Adarrah en Tanaris et emparez-vous d\'Uldum et de ses ressources pour la Horde.', 'Aller à Uldum', 'Interface\\questionframe\\answer-warboard-cata-uldum.blp', 27726, 829, -11018.6e0, -1263.54e0, 13.52e0, 4.85e0, 'Vous avez été téléporté à Uldum !', 1, 'Uldum', 'The ancient lands of Uldum have been uncovered, revealing their age-old treasures and Titan technology to the armies of the Alliance and the Horde.\n\nJoin Adarrah\'s caravan in Tanaris and seize Uldum and its resources for the Horde.', 'Travel to Uldum', 'You have been teleported to Uldum!'),
(2, 1, 1, 'Mont Hyjal', 'Les sbires d\'Aile de mort au mont Hyjal cherchent à faire ployer Azeroth sous la puissance dévastatrice du seigneur du Feu !\n\nParlez à l\'émissaire cénarien Sabot-Noir, à Orgrimmar, pour accéder au mont Hyjal.', 'Aller à Hyjal', 'Interface\\questionframe\\answer-warboard-cata-mounthyjal.blp', 27721, 1, 5534.08e0, -3624.69e0, 1567.04e0, 5.39048e0, 'Vous avez été téléporté au Mont Hyjal !', 1, 'Mount Hyjal', 'Deathwing\'s minions at Mount Hyjal seek to bring Azeroth to its knees beneath the devastating might of the Firelord!\n\nSpeak with Cenarion emissary Blackhoof in Orgrimmar to gain access to Mount Hyjal.', 'Travel to Hyjal', 'You have been teleported to Mount Hyjal!'),
(3, 1, 2, 'Le Tréfonds', 'Le Cercle terrestre mène une lutte acharnée pour juguler les énergies chaotiques qui se déversent par la faille reliant le Tréfonds à Azeroth, dans le Maelström.\n\nAidez-le à condamner la brèche et sauvez notre monde d\'une destruction certaine.', 'Aller au Tréfonds', 'Interface\\questionframe\\answer-warboard-cata-deepholm.blp', 27722, 852, 854.924e0, 1080.96e0, -12.5196e0, 4.54772e0, 'Vous avez été téléporté au Tréfonds !', 1, 'Deepholm', 'The Earthen Ring is waging a desperate struggle to contain the chaotic energies pouring through the rift linking Deepholm to Azeroth, within the Maelstrom.\n\nHelp them seal the breach and save our world from certain destruction.', 'Travel to Deepholm', 'You have been teleported to Deepholm!'),
(4, 0, 0, 'Uldum', 'Les anciennes terres d\'Uldum ont été mises au jour, livrant leurs trésors ancestraux et la technologie des Titans aux armées de l\'Alliance et de la Horde.\n\nRejoignez la caravane d\'Adarrah en Tanaris et emparez-vous d\'Uldum et de ses ressources pour la Horde.', 'Aller à Uldum', 'Interface\\questionframe\\answer-warboard-cata-uldum.blp', 27721, 829, -11018.6e0, -1263.54e0, 13.52e0, 4.85e0, 'Vous avez été téléporté à Uldum !', 1, 'Uldum', 'The ancient lands of Uldum have been uncovered, revealing their age-old treasures and Titan technology to the armies of the Alliance and the Horde.\n\nJoin Adarrah\'s caravan in Tanaris and seize Uldum and its resources for the Horde.', 'Travel to Uldum', 'You have been teleported to Uldum!'),
(5, 0, 1, 'Mont Hyjal', 'Les sbires d\'Aile de mort au mont Hyjal cherchent à faire ployer Azeroth sous la puissance dévastatrice du seigneur du Feu !\n\nParlez à l\'émissaire cénarien Sabot-Noir, à Orgrimmar, pour accéder au mont Hyjal.', 'Aller à Hyjal', 'Interface\\questionframe\\answer-warboard-cata-mounthyjal.blp', 27726, 1, 5534.08e0, -3624.69e0, 1567.04e0, 5.39048e0, 'Vous avez été téléporté au Mont Hyjal !', 1, 'Mount Hyjal', 'Deathwing\'s minions at Mount Hyjal seek to bring Azeroth to its knees beneath the devastating might of the Firelord!\n\nSpeak with Cenarion emissary Blackhoof in Orgrimmar to gain access to Mount Hyjal.', 'Travel to Hyjal', 'You have been teleported to Mount Hyjal!'),
(6, 0, 2, 'Le Tréfonds', 'Le Cercle terrestre mène une lutte acharnée pour juguler les énergies chaotiques qui se déversent par la faille reliant le Tréfonds à Azeroth, dans le Maelström.\n\nAidez-le à condamner la brèche et sauvez notre monde d\'une destruction certaine.', 'Aller au Tréfonds', 'Interface\\questionframe\\answer-warboard-cata-deepholm.blp', 27727, 852, 854.924e0, 1080.96e0, -12.5196e0, 4.54772e0, 'Vous avez été téléporté au Tréfonds !', 1, 'Deepholm', 'The Earthen Ring is waging a desperate struggle to contain the chaotic energies pouring through the rift linking Deepholm to Azeroth, within the Maelstrom.\n\nHelp them seal the breach and save our world from certain destruction.', 'Travel to Deepholm', 'You have been teleported to Deepholm!'),
(7, 1, 3, 'Vashj\'ir', 'Tous les membres de la Horde en état de porter les armes sont sommés de se présenter au commandant Thorak dans la baie de Lamepoing, en Durotar.\r\n\r\nAujourd’hui plus que jamais, votre aide est requise pour combattre notre pire ennemi : l’Alliance !\r\n\r\nPour vous rendre dans la baie de Lamepoing, vous devez faire route vers le sud en partant des portes d’Orgrimmar, et pénétrer en Durotar. Une fois là, suivez la piste de l’est qui mène jusqu’à la côte. Thorak vous attendra à son poste, près des quais.', 'Aller à Vashj\'ir', 'Interface\\questionframe\\answer-warboard-cata-vashjir.blp', 27718, 0, -5332.27e0, 3898.77e0, 3.56735e0, 3.54136e0, 'Vous avez été téléporté à Vashj\'ir !', 1, 'Vashj\'ir', 'All Horde members fit to bear arms are ordered to report to Commander Thorak in Bladefist Bay, Durotar.\r\n\r\nToday more than ever, everyone\'s help is needed to fight our worst enemy: the Alliance!\r\n\r\nTo reach Bladefist Bay, head south from the gates of Orgrimmar into Durotar. Once there, follow the eastern trail to the coast. Thorak will be waiting at his post, near the docks.', 'Travel to Vashj\'ir', 'You have been teleported to Vashj\'ir!'),
(8, 0, 3, 'Vashj\'ir', 'Par ordre de Sa Majesté le roi Anduin Wrynn, tous les citoyens de l’Alliance en état de porter les armes doivent se présenter au recruteur Burns, au port de Hurlevent.\r\n\r\nLes récentes attaques de la Horde sur nos navires marchands doivent être réprimées avec force et rapidité !\r\n\r\nLe port de Hurlevent se trouve dans la région nord-ouest de Hurlevent.', 'Aller à Vashj\'ir', 'Interface\\questionframe\\answer-warboard-cata-vashjir.blp', 27724, 0, -5332.27e0, 3898.77e0, 3.56735e0, 3.54136e0, 'Vous avez été téléporté à Vashj\'ir !', 1, 'Vashj\'ir', 'By order of His Majesty King Anduin Wrynn, all Alliance citizens fit to bear arms must report to Recruiter Burns at Stormwind Harbor.\r\n\r\nThe Horde\'s recent attacks on our merchant ships must be swiftly and forcefully put down!\r\n\r\nStormwind Harbor is located in the northwestern part of Stormwind.', 'Travel to Vashj\'ir', 'You have been teleported to Vashj\'ir!'),
(9, 1, 4, 'Outreterre', 'Tous les membres de la Horde en état de porter les armes sont sommés de se présenter au général de division Orion, à l’escalier du Destin.\r\n\r\nVos compétences sont requises pour combattre la Légion ardente, dont la présence souille les vestiges désolés de l’Outreterre.', 'Aller à l\'Outreterre', 'Interface\\questionframe\\answer-warboard-bc-hellfirepeninsula.blp', 28705, 530, -247.29e0, 910.638e0, 84.3798e0, 1.49341e0, 'Vous avez été téléporté à l’Outreterre !', 1, 'Outland', 'All Horde members fit to bear arms are ordered to report to Major General Orion at the Stair of Destiny.\r\n\r\nYour skills are needed to fight the Burning Legion, whose presence defiles the desolate remnants of Outland.', 'Travel to Outland', 'You have been teleported to Outland!'),
(10, 0, 4, 'Outreterre', 'Par ordre de Sa Majesté le roi Anduin Wrynn, tous les citoyens de l’Alliance en état de porter les armes doivent se présenter au commandant Duron dans la péninsule des Flammes infernales.\r\n\r\nLes troupes expéditionnaires ont besoin de votre aide pour venir à bout des armées démoniaques de la Légion ardente !', 'Aller à l\'Outreterre', 'Interface\\questionframe\\answer-warboard-bc-hellfirepeninsula.blp', 28708, 530, -247.29e0, 910.638e0, 84.3798e0, 1.49341e0, 'Vous avez été téléporté à l’Outreterre !', 1, 'Outland', 'By order of His Majesty King Anduin Wrynn, all Alliance citizens fit to bear arms must report to Commander Duron in Hellfire Peninsula.\r\n\r\nThe expeditionary forces need your help to overcome the Burning Legion\'s demonic armies!', 'Travel to Outland', 'You have been teleported to Outland!'),
(11, 1, 5, 'Orneval', 'Tous les membres de la Horde en état de porter les armes sont sommés de se présenter à Kadrak au rempart de Mor’shan, sur la frontière entre les Tarides du Nord et Orneval. \r\n\r\nAidez nos forces à bouter les Elfes de la nuit hors de la forêt afin que nous utilisions ses ressources pour notre population !', 'Aller à Orneval', 'Interface\\questionframe\\answer-warboard-classic-ashenvale.blp', 28493, 0, 0.0e0, 0.0e0, 0.0e0, 0.0e0, 'Vous avez été téléporté à Orneval !', 1, 'Ashenvale', 'All Horde members fit to bear arms are ordered to report to Kadrak at Mor\'shan Rampart, on the border between Northern Barrens and Ashenvale. \r\n\r\nHelp our forces drive the Night Elves out of the forest so we may put its resources to use for our people!', 'Travel to Ashenvale', 'You have been teleported to Ashenvale!'),
(12, 0, 5, 'les Carmines', 'Par ordre de Sa Majesté le roi Anduin Wrynn, tous les citoyens de l’Alliance en état de porter les armes doivent se présenter au capitaine de la garde Parker à la Tour de guet, dans les Carmines.\r\n\r\nLes troupes du capitaine Parker ont essuyé des attaques de Gnolls et d’Orcs en maraude. Les braves gens de Comté-du-Lac sont en danger et ont besoin de votre protection.', 'Aller au Carmines', 'Interface\\questionframe\\answer-warboard-classic-redridgemountains.blp', 28563, 0, 0.0e0, 0.0e0, 0.0e0, 0.0e0, 'Vous avez été téléporté au Carmines !', 1, 'Redridge Mountains', 'By order of His Majesty King Anduin Wrynn, all Alliance citizens fit to bear arms must report to Guard Captain Parker at the Watch Tower, in Redridge.\r\n\r\nCaptain Parker\'s troops have come under attack from marauding gnolls and orcs. The good people of Lakeshire are in danger and need your protection.', 'Travel to Redridge', 'You have been teleported to Redridge Mountains!'),
(13, 1, 6, 'Tarides du Sud', 'Tous les membres de la Horde en état de porter les armes sont sommés de se présenter à Nura la Guide, à la Haute-route, dans les Tarides du Sud. Suite aux récentes victoires de l’Alliance dans les Tarides, nos routes de ravitaillement sont menacées. \r\n\r\nSi nous en perdions le contrôle, nos guerriers se retrouveraient complètement isolés. Nous devons réagir !', 'Aller au Tarides', 'Interface\\questionframe\\answer-warboard-classic-southernbarrens.blp', 28549, 0, 0.0e0, 0.0e0, 0.0e0, 0.0e0, 'Vous avez été téléporté au Tarides du Sud !', 1, 'Southern Barrens', 'All Horde members fit to bear arms are ordered to report to Nura the Trailblazer at the High Road, in Southern Barrens. Following the Alliance\'s recent victories in the Barrens, our supply lines are under threat. \r\n\r\nIf we were to lose control of them, our warriors would find themselves completely cut off. We must act!', 'Travel to the Barrens', 'You have been teleported to Southern Barrens!'),
(14, 0, 6, 'Tarides du Sud', 'Par ordre de Sa Majesté le roi Anduin Wrynn, tous les citoyens de l’Alliance en état de porter les armes doivent se présenter au chef des docks Lewis, près du fort de Guet-du-Nord.\r\n\r\nNos vaillants soldats ont remporté de formidables batailles dans les Tarides, mais ont payé le prix fort. Afin de conserver l’avantage que nous confèrent nos victoires, nous avons besoin de vous.', 'Aller au Tarides', 'Interface\\questionframe\\answer-warboard-classic-southernbarrens.blp', 28551, 0, 0.0e0, 0.0e0, 0.0e0, 0.0e0, 'Vous avez été téléporté au Tarides du Sud !', 1, 'Southern Barrens', 'By order of His Majesty King Anduin Wrynn, all Alliance citizens fit to bear arms must report to Dockmaster Lewis, near Northwatch Hold.\r\n\r\nOur brave soldiers have won formidable battles in the Barrens, but at a heavy cost. To hold on to the advantage our victories have earned us, we need you.', 'Travel to the Barrens', 'You have been teleported to Southern Barrens!'),
(15, 1, 7, 'Tarides du Nord', 'Tous les membres de la Horde, physiquement aptes, ont ordre de se présenter à Kargal Balafre-glorieuse, au poste de Guet-Lointain, dans les Tarides du Nord.\r\n\r\nPlus que jamais, l’aide de tous est indispensable pour défendre les Tarides du Nord contre les incursions des hurans et des centaures !', 'Aller au Tarides', 'Interface\\questionframe\\answer-warboard-classic-northernbarrens.blp', 28494, 0, 0.0e0, 0.0e0, 0.0e0, 0.0e0, 'Vous avez été téléporté au Tarides du Nord !', 1, 'Northern Barrens', 'All Horde members fit for duty are ordered to report to Kargal Battlescar at the Far Watch Post, in Northern Barrens.\r\n\r\nMore than ever, everyone\'s help is needed to defend Northern Barrens against Quilboar and centaur incursions!', 'Travel to the Barrens', 'You have been teleported to Northern Barrens!'),
(16, 0, 7, 'Marche de l\'Ouest', 'Par ordre de Sa Majesté le roi Anduin Wrynn, tous les citoyens de l’Alliance en état de porter les armes doivent se présenter au lieutenant Horatio Laine à la ferme des Jansen.\r\n\r\nLa marche de l’Ouest est submergée par les mendiants et les vagabonds et la criminalité explose. Votre aide est requise afin de rétablir l’ordre public.', 'Marche de l\'Ouest', 'Interface\\questionframe\\answer-warboard-classic-westfall.blp', 28562, 0, 0.0e0, 0.0e0, 0.0e0, 0.0e0, 'Vous avez été téléporté à la Marche de l\'Ouest !', 1, 'Westfall', 'By order of His Majesty King Anduin Wrynn, all Alliance citizens fit to bear arms must report to Lieutenant Horatio Laine at Jansen Stead.\r\n\r\nWestfall is being overrun by beggars and vagrants, and crime is on the rise. Your help is needed to restore public order.', 'Westfall', 'You have been teleported to Westfall!');

-- 16 ligne(s)
SET FOREIGN_KEY_CHECKS = 1;
